/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Tela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valor_nota = new javax.swing.JComboBox<>();
        Valor_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Valor_idade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Resultado = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matriz-bordado-mix-mateus-bordado-removebg-preview.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Digite seu Nome: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Digite sua Idade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        valor_nota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valor_nota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        valor_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_notaActionPerformed(evt);
            }
        });
        getContentPane().add(valor_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        Valor_nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.darkGray));
        Valor_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(Valor_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 97, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Escolha a nota de Avaliacao");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Valor_idade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.darkGray));
        getContentPane().add(Valor_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 97, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("ENVIAR RESPOSTA ");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.darkGray));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        Resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Resultado.setText("Informação ");
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_notaActionPerformed

    private void Valor_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        String nome = Valor_nome.getText();
        int idade = (Integer.parseInt( Valor_idade.getText()));
       if(idade ==18){
               }else if(idade >18 ){
                   
               }else{
                   String mensagem = nome + " Informamos que so maiores de idade podem participar da nossa pesquisa .";
                   Resultado.setText(mensagem);
                   return;
                   
               } 
        int nota = (Integer.parseInt(valor_nota.getSelectedItem().toString()));
        String mensagem = nome + " agradecemos por sua nota " + nota + "." ;
        
        Resultado.setText(mensagem);
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JTextField Valor_idade;
    private javax.swing.JTextField Valor_nome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> valor_nota;
    // End of variables declaration//GEN-END:variables
}
